name: OPUS 4 Documentation
siteName: OPUS 4 Documentation
description: OPUS 4 document repository software user and developer documentation.

author: Jens Schwidder

author_email: schwidder@zib.de

url: https://opus4.github.io

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"


